import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Chip } from "./Chip";
const DIETARY = ["Vegan", "Vegetarian", "Halal", "Kosher", "Gluten-Free", "Nut-Free", "Dairy-Free"];
const CUISINES = ["Moroccan", "Italian", "Japanese", "Spanish", "Lebanese", "Mexican", "Indian", "Turkish", "French", "Greek"];
const PRODUCT_TYPES = ["Baked Goods", "Bread", "Cake", "Frozen Meals", "Jam & Preserves", "Pasta", "Desserts"];
const TIMES = ["Breakfast", "Brunch", "Lunch", "Dinner", "Late Night"];
export default function FilterPanel({ open, onClose }) {
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 bg-ink/40 z-40 transition-opacity " +
                    (open ? "opacity-100 pointer-events-auto" : "opacity-0 pointer-events-none"), onClick: onClose }), _jsxs("aside", { className: "fixed top-0 right-0 bottom-0 z-50 w-full max-w-[440px] bg-cream-50 border-l-2 border-ink shadow-sheet transition-transform " +
                    (open ? "translate-x-0" : "translate-x-full"), children: [_jsxs("div", { className: "flex items-center justify-between px-5 py-4 border-b border-ink/10", children: [_jsx("div", { className: "font-display font-extrabold text-2xl", children: "Filters" }), _jsx("button", { onClick: onClose, "aria-label": "Close filters", className: "w-9 h-9 rounded-full border-2 border-ink grid place-items-center", children: _jsxs("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.5", strokeLinecap: "round", children: [_jsx("line", { x1: "6", y1: "6", x2: "18", y2: "18" }), _jsx("line", { x1: "18", y1: "6", x2: "6", y2: "18" })] }) })] }), _jsxs("div", { className: "overflow-y-auto h-[calc(100%-72px-72px)] px-5 py-5 space-y-6", children: [_jsx(Section, { title: "Listing Type", children: _jsxs("div", { className: "flex gap-2", children: [_jsx(Chip, { variant: "amber", children: "All" }), _jsx(Chip, { children: "\uD83C\uDF7D Table only" }), _jsx(Chip, { children: "\uD83D\uDECD Market only" })] }) }), _jsx(Section, { title: "Dietary requirements", children: _jsx("div", { className: "flex flex-wrap gap-1.5", children: DIETARY.map((t) => (_jsx(Chip, { children: t }, t))) }) }), _jsx(Section, { title: "Budget", hint: "\u20AC3 \u2014 \u20AC100+", children: _jsx("input", { type: "range", min: 3, max: 100, defaultValue: 30, className: "w-full accent-amber" }) }), _jsx(Section, { title: "Cuisine", children: _jsx("div", { className: "flex flex-wrap gap-1.5", children: CUISINES.map((t) => (_jsx(Chip, { children: t }, t))) }) }), _jsx(Section, { title: "Product type", children: _jsx("div", { className: "flex flex-wrap gap-1.5", children: PRODUCT_TYPES.map((t) => (_jsx(Chip, { children: t }, t))) }) }), _jsx(Section, { title: "Time (Tables)", children: _jsx("div", { className: "flex flex-wrap gap-1.5", children: TIMES.map((t) => (_jsx(Chip, { children: t }, t))) }) })] }), _jsxs("div", { className: "absolute left-0 right-0 bottom-0 px-5 py-4 border-t border-ink/10 bg-cream-50 flex items-center gap-3", children: [_jsx("button", { className: "flex-1 py-3 rounded-2xl border-2 border-ink font-semibold", children: "Clear" }), _jsx("button", { onClick: onClose, className: "flex-1 py-3 rounded-2xl border-2 border-ink bg-ink text-cream-50 font-semibold", children: "Show results" })] })] })] }));
}
function Section({ title, hint, children, }) {
    return (_jsxs("div", { children: [_jsxs("div", { className: "flex items-baseline justify-between mb-2", children: [_jsx("h3", { className: "font-display font-bold text-base", children: title }), hint && _jsx("span", { className: "text-xs text-ink/50", children: hint })] }), children] }));
}
